import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
option_as_alt = "OnlyLeft"
opacity = 0.85


[window.padding]
x = 18
y = 16

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
