#!/usr/bin/env bash
set -euo pipefail

WORKTREES_DIR="./worktrees/"

main() {
  case "${1-}" in
  work:issue)
    : "${2?Usage: $0 work:issue <session>}"
    tmux_start "$2"
    tmux_command "$2" "worktree new $2 && cd worktrees/$2 && mise trust"
    tmux_command "$2" "claude 'Please implement linear issue $2. Make sure to make a plan first and have me approve it before starting. When you are done. Please commit, and make a pull-request where you briefly and precisely descript what is implemented. Declare at the top of the description that it is implemented and described by AI'"
    tmux_switch "$2"
    ;;
  *)
    echo "Usage: $0 work:issue <session>" >&2
    exit 1
    ;;
  esac
}

tmux_start() {
  local session=$1
  if ! tmux has-session -t "$session" 2>/dev/null; then
    tmux new-session -d -s "$session" -n claude
  fi
}

tmux_switch() {
  local session=$1
  if [[ -n ${TMUX-} ]]; then
    tmux switch-client -t "$session" # inside tmux
  else
    tmux attach -t "$session" # outside tmux
  fi
}

tmux_command() {
  local session=$1
  local cmd=$2
  tmux send-keys -t "$session:claude" "$cmd" C-m
}

main "$@"
