#!/usr/bin/env bash

set -euo pipefail

WORKTREES_DIR="./worktrees/"

function main() {
  case "$1" in
  new)
    echo "Creating worktree"
    create_worktree $2
    ;;
  *)
    echo "Error"
    ;;
  esac
}

create_worktree() {
  local branch_name="$1"
  local worktree_path="$WORKTREES_DIR/$branch_name"

  git worktree add "$worktree_path" -b "$branch_name"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
